name: "GitHub Monogamy"

on:
  issues:
    types: [opened, reopened, transferred]

jobs:
  turn-limit:
    runs-on: ubuntu-latest
    steps:
      - name: Expel forbidden lures
        uses: actions/github-script@v7
        with:
          script: |
            const maxOpen = 8;
            const comment = `## Issue closed by [GitHub Monogamy](https://github.com/hacker1024/github-monogamy)

            Too many people are waiting for ${context.repo.owner}'s resolution.  
            They must close existing issues, and then they can receive new ones.  
            Research shows this leads to less bugs.
            `;

            const issues = await github.rest.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: "open",
              sort: "created",
              direction: "desc"
            });

            const temptations = issues.data.length - maxOpen;
            if (temptations <= 0) return;

            for (let i = 0; i < temptations; ++i) {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issues.data[i].number,
                body: comment
              });

              await github.rest.issues.update({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issues.data[i].number,
                state: "closed"
              });
            }
